### Register a user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "username": "otin",
  "password": "otin123",
  "birthdate": "1990-01-01",
  "sex": "male",
  "contact": "555-1234",
  "region": "Region XI",
  "province": "Davao del Sur",
  "city": "Davao City",
  "barangay": "33-D",
  "postal_code": "8000"

}