import LitratoSidebar from "../../../Litratocomponents/sidebar";
import AuthGuard from "../../../Litratocomponents/AuthGuard";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Antic_Didone } from "next/font/google";

const anticDidone = Antic_Didone({
  variable: "--font-antic-didone",
  subsets: ["latin"],
  weight: "400",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LITRATOBYAM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen bg-gray-100">
  <AuthGuard />
        {/* Sidebar fixed on the left */}
        <div className="fixed left-0 top-0 h-full">
          <LitratoSidebar />
        </div>

        {/* Main content shifted right */}
        <main className="ml-64 flex-1 pl-4 overflow-y-auto">{children}</main>
      </body>
    </html>
  );
}
