import "bootstrap/dist/css/bootstrap.min.css";
import CustomerLayoutShell from "../../../Litratocomponents/CustomerLayoutShell";
import AuthGuard from "../../../Litratocomponents/AuthGuard";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Antic_Didone } from "next/font/google";

const anticDidone = Antic_Didone({
  variable: "--font-antic-didone",
  subsets: ["latin"],
  weight: "400",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LITRATOBYAM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthGuard>
          <CustomerLayoutShell>{children}</CustomerLayoutShell>
        </AuthGuard>
      </body>
    </html>
  );
}
