import "bootstrap/dist/css/bootstrap.min.css";
import LitratoSidebar from "../../../Litratocomponents/sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Antic_Didone } from "next/font/google";

const anticDidone = Antic_Didone({
  variable: "--font-antic-didone",
  subsets: ["latin"],
  weight: "400",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LITRATOBYAM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${anticDidone.variable} flex antialiased`}
      >
        <LitratoSidebar></LitratoSidebar>
        <main className="flex-1"> {children}</main>
      </body>
    </html>
  );
}
